### PR TITLE
CMakeLists.txt: fix compilation on linux

### PR DESCRIPTION
**Pull request by dhead666**
This commit fix compilation on my system, Arch Linux, x86_64.

### CODE REVIEW

**Comment by dhead666** [comment]
I'm far from expert but I updated CMakeLists.txt, now I can build adsp.biquad.filters on my system (though I didn't tested the addon in kodi yet).

**Comment by dhead666** [comment]
ping @AchimTuran

**Comment by AchimTuran** [comment]
@dhead666 thanks for your work.

At the moment I'm very busy with GSoC, so I can't check the build on Windows.

> I'm far from expert but I updated CMakeLists.txt

Me too, I'm still learning CMake.

**Comment by dhead666** [comment]
Indentation fixed.

**Comment by dhead666** [comment]
@AchimTuran 

I updated the PR, added [UseMultiArch.cmake](https://github.com/Pulse-Eight/platform/blob/master/UseMultiArch.cmake) from Pulse-Eight's platform repo.

I kept the commit for adding the GCC flag separate, it should be removed if/when you'll change the preprocessor macro from `#elif defined(TARGET_LINUX)` to just `else` in order to cover all POSIX platforms.

**Comment by AchimTuran** [comment]
Hey thanks for your work. Looks good, but before merge it I will test it with my windows- and my linux machine.

I hope it is okay for that the merge will be next month. Sorry currently I'm very busy.

**Pull request merged**
